<?php
/**
 * E2E Helper - Disable event tracking to simulate user consent = NO
 *
 * This helper creates/removes a must-use plugin that disables Facebook pixel and CAPI events,
 * simulating a scenario where the user has NOT consented to tracking.
 *
 * Usage: php disable-tracking-consent.php enable|disable
 */

$wp_path = getenv('WORDPRESS_PATH') . '/wp-load.php';

if (!file_exists($wp_path)) {
    echo json_encode([
        'success' => false,
        'error' => 'WordPress not found at: ' . $wp_path
    ]);
    exit(1);
}

require_once($wp_path);

// Get command (enable or disable tracking)
$command = isset($argv[1]) ? $argv[1] : 'disable';

// Path to mu-plugins directory
$mu_plugins_dir = WP_CONTENT_DIR . '/mu-plugins';
$mu_plugin_file = $mu_plugins_dir . '/disable-facebook-tracking-for-e2e-test.php';

try {
    if ($command === 'disable') {
        // Create mu-plugins directory if it doesn't exist
        if (!file_exists($mu_plugins_dir)) {
            mkdir($mu_plugins_dir, 0755, true);
        }

        // Create mu-plugin that disables tracking
        $mu_plugin_content = <<<'PHP'
<?php
/**
 * Must-use plugin for E2E testing
 * Disables Facebook tracking to simulate user consent = NO
 * This file is auto-generated by tests and should be auto-removed after tests
 */

// Disable Facebook pixel and CAPI events by returning false
add_filter('facebook_for_woocommerce_integration_pixel_enabled', '__return_false', 99);
PHP;

        file_put_contents($mu_plugin_file, $mu_plugin_content);

        echo json_encode([
            'success' => true,
            'message' => 'Event tracking disabled (simulating user consent = NO)',
            'mu_plugin_created' => $mu_plugin_file
        ]);
    } else if ($command === 'enable') {
        // Remove the mu-plugin to enable tracking
        if (file_exists($mu_plugin_file)) {
            unlink($mu_plugin_file);
        }

        echo json_encode([
            'success' => true,
            'message' => 'Event tracking enabled (simulating user consent = YES)',
            'mu_plugin_removed' => $mu_plugin_file
        ]);
    } else {
        echo json_encode([
            'success' => false,
            'error' => 'Invalid command. Use "enable" or "disable"'
        ]);
        exit(1);
    }
} catch (Exception $e) {
    echo json_encode([
        'success' => false,
        'error' => $e->getMessage()
    ]);
    exit(1);
}
