name: "Prepare New Release"
# run-name: Prepare New Release `${{ github.event.inputs.type }}/${{ github.event.inputs.version }}` from by @${{ github.actor }}

# **What it does**: Does release preparation: creates the release branch and the PR with a checklist.
# **Why we have it**: To support devs automating a few manual steps and to leave a nice reference for consumers.

on:
  # workflow_dispatch:
  #   inputs:
  #     ## In the future we could infer that version from the changelog, or bump it via major|minor|patch.
  #     version:
  #       description: "Version number to be released"
  #       required: true
  push:
    branches:
      - 'tzahgr/prepare_release'


jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Changelog
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const version = process.env.VERSION;
            const releaseNotes = process.env.RELEASE_NOTES;
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${version}`,
              target_commitish: 'release/current',
              name: `Release ${version}`,
              body: releaseNotes,
              draft: true,
            });
            const response = await github.rest.repos.generateReleaseNotes( {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v3.5.4',
              previous_tag_name: 'v3.5.3',
            } );

            core.summary
              .addHeading("Output")
              .addRaw(response.data)
              .write();
