name: "Prepare New Release"
# run-name: Prepare New Release `${{ github.event.inputs.type }}/${{ github.event.inputs.version }}` from by @${{ github.actor }}

# **What it does**: Does release preparation: creates the release branch and the PR with a checklist.
# **Why we have it**: To support devs automating a few manual steps and to leave a nice reference for consumers.

on:
  # workflow_dispatch:
  #   inputs:
  #     ## In the future we could infer that version from the changelog, or bump it via major|minor|patch.
  #     version:
  #       description: "Version number to be released"
  #       required: true
  push:
    branches:
      - 'tzahgr/prepare_release'

permissions:
  contents: write

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0

      - name: Set Version
        id: set_version
        run: echo "new_version=9.9.9" >> "$GITHUB_OUTPUT"

      - name: Check if branch exists
        uses: actions/github-script@v7
        env:
          NEW_VERSION: ${{ steps.set_version.outputs.new_version }}
        with:
          script: |
            const newVersion = process.env.NEW_VERSION.trim();            
            const branch = `release/${newVersion}`;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              await github.rest.repos.getBranch({
                owner,
                repo,
                branch,
              });

              core.setFailed(`Branch "${branch}" already exists.`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`✅ Branch "${branch}" does not exist.`);
              } else {
                throw error;
              }
            }

      - name: Get latest release tag
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const tag = latestRelease.data.tag_name;
            core.setOutput("latest_tag", tag);
            console.log("Latest release tag:", tag);

      - name: Get commits since latest release
        id: get_commits
        run: |
          git fetch origin tag ${{ steps.get_release.outputs.latest_tag }}
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          git rev-list ${{ steps.get_release.outputs.latest_tag }}..HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build changelog from PRs
        id: changelog
        uses: actions/github-script@v7
        env:
          COMMITS: ${{ steps.get_commits.outputs.commits }}
          NEW_VERSION: ${{ steps.set_version.outputs.new_version }}
        with:
          script: |
            const newVersion = process.env.NEW_VERSION.trim();
            const commits = process.env.COMMITS.trim().split('\n');
            const changelog = [];

            for (const sha of commits) {
              const commit = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: sha,
              });

              const msg = commit.data.commit.message;
              const prMatch = msg.match(/\(#(\d+)\)/);
              if (!prMatch) {
                continue;
              }

              const prNumber = parseInt(prMatch[1], 10);
              pr = (await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              })).data;
              const labelPrefix = "changelog:";
              const changeLogLabels = pr.labels.map(l => l.name).filter((l) => l.startsWith(labelPrefix)).map(l => l.replace(labelPrefix, "").trim());
              if (changeLogLabels.length === 0){
                continue;
              }

              const changeLogLabel = changeLogLabels[0];
              if (changeLogLabel.toLowerCase() === 'none'){
                continue;
              }

              changelog.push(`* ${changeLogLabel.charAt(0).toUpperCase()}${changeLogLabel.slice(1)} - ${pr.title} by @${pr.user.login} in #${prNumber}`);              
            }

            const date = new Date();
            const output = `= ${newVersion} - ${date.toISOString().slice(0, 10)} =\n${changelog.join('\n')}\n`;
            core.setOutput('changelog', output);
            console.log(output);

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch locally
        env:
          NEW_VERSION: ${{ steps.set_version.outputs.new_version }}
        run: |
          git checkout -b "release/$NEW_VERSION"

      - name: Update package.json
        env:
          NEW_VERSION: ${{ steps.set_version.outputs.new_version }}
        run: |
          sed -i -E "s/^  \"version\":[[:space:]]*\"[^\"]*\"[[:space:]]*,/  \"version\": \"${NEW_VERSION}\",/" "package.json"
          git diff

      - name: Commit changes
        env:
          NEW_VERSION: ${{ steps.set_version.outputs.new_version }}
        run: |
          git status
          git add .
          git commit -m "Updating version to $NEW_VERSION"
          git log -n 5

