name: Release Plugin

on:
  push:
    branches:
      - 'release/current'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - uses: actions/checkout@v1

      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Validate Git tag
        run: |
          if [ $(git tag -l "v${{ steps.package-version.outputs.current-version}}") ]; then
            echo "Git tag exist" 1>&2
            exit 1
          fi

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache-dependency-path: './package-lock.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci || npm install
          composer install
      
      - name: Build plugin
        run: |
          npm run build
          if [ -f "facebook-for-woocommerce.zip" ]; then
            echo "build_success=true" >> $GITHUB_OUTPUT
            echo "filesize=$(du -h facebook-for-woocommerce.zip | cut -f1)" >> $GITHUB_OUTPUT
          else
            echo "build_success=false" >> $GITHUB_OUTPUT
            echo "Build error" 1>&2
            exit 1
          fi
      
      - name: Store built plugin
        uses: actions/upload-artifact@master
        continue-on-error: true
        with:
          name: facebook-for-woocommerce
          path: facebook-for-woocommerce.zip

      - name: Install SVN
        run: sudo apt-get install subversion -y

      - name: Checkout SVN Repository
        run: svn co https://plugins.svn.wordpress.org/facebook-for-woocommerce/ woocommerce_svn --quiet --non-interactive

      - name: Validate SVN tag
        run: |
          if [ -d "woocommerce_svn/tags/${{ steps.package-version.outputs.current-version}}" ]; then
            echo "SVN tag directory exist" 1>&2
            exit 1
          fi

      # - name: Delete file - temp
      #   run: rm woocommerce_svn/tags/1.10.0/changelog.txt

      - name: Commit to SVN
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          cd woocommerce_svn
          rm -rf trunk
          mv ../facebook-for-woocommerce.zip ./
          echo "Unzipping the atrifact"
          unzip facebook-for-woocommerce.zip
          mv facebook-for-woocommerce trunk
          rm facebook-for-woocommerce.zip
          svn add --force .
          svn st | grep ^! | awk '{print $2}' | xargs -r svn rm
          svn status
          echo "Tagging version ${{ steps.package-version.outputs.current-version}}"
          svn cp trunk "tags/${{ steps.package-version.outputs.current-version}}"
          echo "Status:"
          svn status


# svn commit -m "Deploy new version ${{ steps.package-version.outputs.current-version}}" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --non-interactive
